input {
  s3 {
    bucket => "cloudtrail-logs-364868683991-ap-south-1-an"
    region => "ap-south-1"
    prefix => "AWSLogs/364868683991/CloudTrail/"
    sincedb_path => "/usr/share/logstash/sincedb_cloudtrail"
    codec => "json"
    gzip_pattern => "\.gz$"
  }
}

filter {

  # Split CloudTrail Records array into individual events
  split {
    field => "Records"
  }

  # Flatten important fields
  mutate {
    rename => {
      "[Records][eventTime]" => "eventTime"
      "[Records][eventName]" => "eventName"
      "[Records][eventSource]" => "eventSource"
      "[Records][awsRegion]" => "awsRegion"
      "[Records][sourceIPAddress]" => "sourceIPAddress"
    }
  }

  # GEO LOCATION ENRICHMENT
  geoip {
    source => "sourceIPAddress"
    target => "geoip"
  }

}

output {

  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "cloudtrail-logs-%{+YYYY.MM.dd}"
  }

  stdout { codec => rubydebug }

}