
services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.0
    container_name: elasticsearch
    restart: unless-stopped

    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m

    cpus: 1
    mem_limit: 768m

    ports:
      - "9200:9200"

    volumes:
      - esdata:/usr/share/elasticsearch/data

    healthcheck:
      test: ["CMD-SHELL", "curl -fs http://localhost:9200 || exit 1"]
      interval: 20s
      retries: 15


  kibana:
    image: docker.elastic.co/kibana/kibana:8.12.0
    container_name: kibana
    restart: unless-stopped

    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - NODE_OPTIONS=--max-old-space-size=256
      - xpack.security.enabled=false

    cpus: 0.3
    mem_limit: 300m

    ports:
      - "5601:5601"

    depends_on:
      elasticsearch:
        condition: service_healthy


  logstash:
    image: docker.elastic.co/logstash/logstash:8.12.0
    container_name: logstash
    restart: unless-stopped
    env_file:
      - .env
    environment:
      # - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      # - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=ap-south-1
      - LS_JAVA_OPTS=-Xms256m -Xmx256m
      - PIPELINE_WORKERS=1

    cpus: 0.4
    mem_limit: 350m

    volumes:
      - ./cloudtrail-s3.conf:/usr/share/logstash/pipeline/logstash.conf:ro

    depends_on:
      elasticsearch:
        condition: service_healthy


volumes:
  esdata: