name: Terraform
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  terraform-init-format-validate:
    name: Init, Format & Validate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Format
        run: terraform fmt -write=true

      - name: Terraform Validate
        run: terraform validate
  terraform-plan:
    name: terraform plan
    runs-on: ubuntu_latest
    needs: terraform-init-format-validate
    steps:
      - name: Terraform plam
        run: terraform plan -out=tfplan
      - name: upload plan file
        uses: actions/upload-artifact@v4
        with:
          name: tfplan
          path: tfplan
  terraform-apply:
    name: terraform apply
    runs-on: ubuntu_latest
    needs: terraform-plan
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    steps:
      - name: download plan file
        uses: actions/download-artifact@v4
        with:
          name: tfplan
          path: tfplan
      - name: Terraform apply
        run: terraform apply --auto-approve tfplan